services:
  postgres:
    image: postgres:16
    container_name: n8n_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_strong_password
      POSTGRES_DB: n8n
    volumes:
      - n8n_pg:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "18080:5678"
    depends_on:
      - postgres
    environment:
      TZ: Europe/Paris
      GENERIC_TIMEZONE: Europe/Paris
      NODE_TLS_REJECT_UNAUTHORIZED=0

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n_strong_password

      # Protection externe
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: very_strong_password_here

      N8N_SECURE_COOKIE: "false"

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
  n8n_pg:
